---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    uses: ome/action-workflows/.github/workflows/gradle_build.yml@v2
  publish_snapshots:
    if: ${{ github.ref == 'refs/heads/master' && github.repository_owner == 'ome' }}
    needs: build
    uses: ome/action-workflows/.github/workflows/gradle_publish.yml@v2
    with:
      ARTIFACTORY_URL: "snapshots"
    secrets:
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags') && github.repository_owner == 'ome'
    uses: ome/action-workflows/.github/workflows/gradle_publish.yml@v2
    with:
      ARTIFACTORY_URL: "releases"
    secrets:
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
